"""
Core entropy-weighted TOPSIS scoring engine for the Sustainability
Evaluator. Pure functions only, no file I/O, so every function here is
independently unit-testable (see tests/test_score_engine.py) without a
database or the real dataset.

Blueprint: sustainability-evaluator-blueprint-v1.4.pdf, sections 3, 5-10.
Sections 3, 5, 6, 7, 8 of that document are marked "Locked" -- any change
to the math here needs a decisions-log entry. Five such changes are
already made and recorded in this plan's Global Constraints
(docs/superpowers/plans/2026-09-13-sustainability-evaluator.md): no
company is ever excluded from the ranking, no imputation is surfaced to
the user, the 0.05 disclosure penalty is kept but applied silently, and
(2026-09-13, user decision) both of section 10's robustness outputs are
dropped entirely: rank stability (the 1,000-draw Dirichlet
re-weighting/re-ranking check) and weight-vs-equal-weights delta (the
"does the weighting even matter" comparison). Neither is computed,
stored, or displayed. The actual score always uses the real entropy
weights only -- equal weighting is never applied anywhere, including as
a comparison.

Reference ranges below are frozen constants, checked against the real
503-company dataset (data/out/sp500_esg_financials_raw.csv) on
2026-09-13, per the written-justification requirement in blueprint
section 6.1:

- env_intensity (Scope 1+2 tCO2e per USD million revenue, log-transformed,
  cost): floor=1.0 (so log >= 0; real data's minimum non-null value is
  0.105, so this floor legitimately compresses a handful of very-clean
  companies to the same best score rather than fabricating a distinction
  the data can't support). hi = ln(97.5th percentile of the real
  distribution) = ln(2344.84) = 7.7599, frozen at first run.
- esg_risk (Sustainalytics Total ESG Risk Score, cost): lo=0, hi=40, the
  vendor's own documented "severe risk" threshold -- kept as-is even
  though 4 real companies score slightly above it (41.7 max); those clip
  to the worst score, which is correct behaviour for a documented
  external ceiling.
- controversy (Sustainalytics controversy level mapped to the 0-5
  ordinal scale already computed in this repo as
  `controversy_score_ordinal`, cost): lo=0, hi=5, the vendor's own
  documented ordinal bound.
- asset_turnover (benefit): lo=0, hi=97.5th percentile of the real
  distribution = 0.6306, frozen at first run (open-ended ratio, no
  natural ceiling per blueprint).
- profit_margin (net margin, benefit): lo=-0.20, the blueprint's example
  distress floor -- checked against real data: only 1.79% of companies
  fall below it, confirming it catches a genuine tail rather than the
  bulk of the index. hi = 97.5th percentile = 0.5209, frozen.
- fcf_margin (benefit): lo=-0.20, same distress floor as profit_margin
  for consistency -- checked: 4.79% of real companies fall below it,
  still a minority tail. hi = 97.5th percentile = 0.6033, frozen.
- leverage (Net debt/EBITDA, target t=1.5, converted to cost via
  d=|x-t|): lo=0, hi=26.8178. The blueprint's own table lists this as
  provisional ("largest distance considered, e.g. 5") pending the real-
  data check section 6.1 requires. That check: at hi=5, 53% of real
  companies would have d > 5 and clip to the worst possible leverage
  score -- not defensible. There's no documented external ceiling for
  this distance (unlike esg_risk's vendor threshold), so per section 6's
  fallback rule the ceiling is set to the 97.5th percentile of the real
  distance distribution instead: 26.8178, frozen at first run. (Real data
  also has one extreme outlier, -603.24, from a near-zero-EBITDA
  denominator; the percentile ceiling naturally clips it without special
  handling, and the winsorised copy in `entropy_weights` below prevents
  it from distorting the leverage axis's weight.)

Correlation check (blueprint section 4 gate, run once against the real,
final normalised+penalised matrix): max |r| = 0.455 (esg_risk vs
controversy). All 7 variables kept, none dropped -- well under the 0.8
threshold. Full matrix: see data/out/sp500_esg_correlation.csv,
generated by 09_score.py.

Entropy-vs-CRITIC decision (blueprint section 7.1): entropy weights on
the real first run range from 4.6% to 36.9%, none reaching the 0.40 cap
-- not lopsided or unstable, so entropy is kept; the CRITIC fallback is
not needed. (`entropy_weights` below still applies the cap/guardrail
unconditionally, since blueprint section 7.1 requires it regardless of
whether it triggers on any given run's data.)
"""
import numpy as np
import pandas as pd

REFERENCE_RANGES = {
    "env_intensity": dict(kind="log_cost", floor=1.0, lo=0.0, hi=7.7599),
    "esg_risk": dict(kind="cost", lo=0.0, hi=40.0),
    "controversy": dict(kind="cost", lo=0.0, hi=5.0),
    "asset_turnover": dict(kind="benefit", lo=0.0, hi=0.6306),
    "profit_margin": dict(kind="benefit", lo=-0.20, hi=0.5209),
    "fcf_margin": dict(kind="benefit", lo=-0.20, hi=0.6033),
    "leverage": dict(kind="target", target=1.5, lo=0.0, hi=26.8178),
}

# score_engine variable name -> raw column name in
# data/out/sp500_esg_financials_raw.csv. env_intensity's raw column
# (env_intensity_per_million) is derived in 09_score.py from the
# existing emissions_intensity_per_revenue column (* 1e6, to get tCO2e
# per USD million revenue instead of per USD).
RAW_COLUMNS = {
    "env_intensity": "env_intensity_per_million",
    "esg_risk": "total_esg_risk_score",
    "controversy": "controversy_score_ordinal",
    "asset_turnover": "asset_turnover",
    "profit_margin": "profit_to_revenue",
    "fcf_margin": "fcf_to_revenue",
    "leverage": "net_debt_to_ebitda",
}

DISCLOSURE_PENALTY = 0.05
WEIGHT_CAP = 0.40
WINSOR_LO, WINSOR_HI = 0.025, 0.975

# Pillar grouping (blueprint section 2/11) -- reporting structure only,
# not a second weighting scheme. Used by pillar_scores below and to
# derive pillar weight shares (e.g. in the frontend).
PILLARS = {
    "environmental": ["env_intensity"],
    "social": ["esg_risk", "controversy"],
    "financial": ["asset_turnover", "profit_margin", "fcf_margin", "leverage"],
}


def normalize_benefit(x: pd.Series, lo: float, hi: float) -> pd.Series:
    """Section 5: benefit variable, more is better. 1 = best."""
    return (x.clip(lower=lo, upper=hi) - lo) / (hi - lo)


def normalize_cost(x: pd.Series, lo: float, hi: float) -> pd.Series:
    """Section 5: cost variable, less is better. 1 = best."""
    return (hi - x.clip(lower=lo, upper=hi)) / (hi - lo)


def normalize_log_cost(x: pd.Series, floor: float, lo: float, hi: float) -> pd.Series:
    """Section 6: heavy-tailed cost variable, log-transformed before the
    fixed-range normalisation described in normalize_cost."""
    logged = np.log(x.clip(lower=floor))
    return normalize_cost(logged, lo, hi)


def normalize_target_as_cost(x: pd.Series, target: float, lo: float, hi: float) -> pd.Series:
    """Section 5: target variable with an optimum in the middle. Converted
    to a distance-from-target, then treated as a cost (less distance is
    better)."""
    distance = (x - target).abs()
    return normalize_cost(distance, lo, hi)


def impute_sector_median(df: pd.DataFrame, sector_col: str, raw_col: str) -> tuple[pd.Series, pd.Series]:
    """Section 6: a missing value is filled with the company's GICS-sector
    median for that variable -- never dropped. Returns (filled, missing)
    where `missing` is a boolean mask kept for internal use only (the
    disclosure penalty in normalize_all below); per this plan's Global
    Constraints it must never be surfaced to the user."""
    sector_median = df.groupby(sector_col)[raw_col].transform("median")
    missing = df[raw_col].isna()
    filled = df[raw_col].where(~missing, sector_median)
    return filled, missing


def normalize_all(df: pd.DataFrame, sector_col: str = "sector") -> tuple[pd.DataFrame, pd.DataFrame]:
    """Runs impute -> direction+range normalise -> silent disclosure
    penalty for every variable in REFERENCE_RANGES, in that order (fixed
    per blueprint section 15). Returns (X, imputed): X is the final 0-1
    matrix that both entropy_weights and topsis_scores read from;
    imputed is a same-shape boolean DataFrame for internal auditing only
    -- per this plan's Global Constraints, never written to any output
    the frontend reads."""
    X = pd.DataFrame(index=df.index)
    imputed = pd.DataFrame(index=df.index)

    for name, spec in REFERENCE_RANGES.items():
        raw_col = RAW_COLUMNS[name]
        filled, missing = impute_sector_median(df, sector_col, raw_col)
        imputed[name] = missing

        if spec["kind"] == "benefit":
            col = normalize_benefit(filled, spec["lo"], spec["hi"])
        elif spec["kind"] == "cost":
            col = normalize_cost(filled, spec["lo"], spec["hi"])
        elif spec["kind"] == "log_cost":
            col = normalize_log_cost(filled, spec["floor"], spec["lo"], spec["hi"])
        elif spec["kind"] == "target":
            col = normalize_target_as_cost(filled, spec["target"], spec["lo"], spec["hi"])
        else:
            raise ValueError(f"unknown reference-range kind: {spec['kind']}")

        X[name] = (col - DISCLOSURE_PENALTY * missing.astype(float)).clip(lower=0.0, upper=1.0)

    return X, imputed


def entropy_divergence(X: pd.DataFrame) -> pd.Series:
    """Section 7's plain entropy-weight formula, with no guardrails --
    this is exactly what section 12's worked example hand-computes.
    entropy_weights below is the production entry point: it runs this
    same formula on a winsorised copy (section 7.1's guardrail), not on
    the raw matrix. Kept as its own function so the core formula is
    testable against the blueprint's worked numbers directly, since
    winsorisation (structurally, via percentile interpolation) always
    perturbs a small/toy matrix even when there's no real thin tail to
    guard against -- it only leaves genuinely spread-out real data
    unchanged, per section 7.1: "the guardrail only activates in the
    thin-tail case it targets"."""
    n = len(X)
    d = {}
    for col in X.columns:
        x = X[col].clip(lower=1e-12)
        p = x / x.sum()
        plogp = (p * np.log(p)).where(p > 0, 0.0)
        e = -(1.0 / np.log(n)) * plogp.sum()
        d[col] = 1.0 - e
    return pd.Series(d)


def entropy_weights(X: pd.DataFrame) -> tuple[pd.Series, pd.Series]:
    """Section 7 (standard entropy weight method) + section 7.1's
    guardrails: entropy is computed on a winsorised (2.5th/97.5th
    percentile clipped) COPY of X, never on X itself -- X is untouched
    and is what topsis_scores reads from. The resulting weights are
    capped at WEIGHT_CAP (0.40); any excess above the cap is
    redistributed proportionally across the uncapped columns. Binary
    variables are out of scope for this project's confirmed 7-variable
    set (see section 11), so that guardrail doesn't apply here.

    Returns (w, d): w sums to 1.0, d is the per-column divergence
    1 - entropy (before the cap is applied, for display/debugging)."""
    Xw = X.copy()
    for col in Xw.columns:
        lo_w, hi_w = Xw[col].quantile(WINSOR_LO), Xw[col].quantile(WINSOR_HI)
        Xw[col] = Xw[col].clip(lower=lo_w, upper=hi_w)

    d = entropy_divergence(Xw)

    if d.sum() == 0:
        w = pd.Series(1.0 / len(d), index=d.index)
    else:
        w = d / d.sum()

    for _ in range(10):
        over = w[w > WEIGHT_CAP].index
        if len(over) == 0:
            break
        excess = (w[over] - WEIGHT_CAP).sum()
        w[over] = WEIGHT_CAP
        under = w.index.difference(over)
        under_sum = w[under].sum()
        if under_sum == 0:
            w[under] = excess / len(under)
        else:
            w[under] = w[under] + excess * (w[under] / under_sum)

    return w, d


def topsis_scores(X: pd.DataFrame, w: pd.Series) -> pd.DataFrame:
    """Section 8: ideal point A+ is all-ones, anti-ideal A- is all-zeros.
    D+/D- are the weighted Euclidean distances to each; score is
    100 * D- / (D+ + D-), so 100 means sitting exactly on the ideal
    (never actually reached -- see blueprint section 8).

    Also computes the per-axis decomposition that backs the explanation
    layer (blueprint section 8): the squared weighted gap to the ideal,
    wj*(1-xij)^2, as a share of the company's total D+^2 -- the "how
    much of this company's distance from the ideal does each variable
    explain" number."""
    w = w.reindex(X.columns)
    gaps_to_ideal = w * (1.0 - X) ** 2
    gaps_to_antiideal = w * X ** 2

    d_plus = np.sqrt(gaps_to_ideal.sum(axis=1))
    d_minus = np.sqrt(gaps_to_antiideal.sum(axis=1))
    score = 100.0 * d_minus / (d_plus + d_minus)

    out = pd.DataFrame({"d_plus": d_plus, "d_minus": d_minus, "score": score}, index=X.index)

    total_gap = gaps_to_ideal.sum(axis=1)
    for col in X.columns:
        out[f"contrib_{col}"] = (gaps_to_ideal[col] / total_gap).fillna(0.0)

    return out


def pillar_scores(X: pd.DataFrame, w: pd.Series, pillars: dict = PILLARS) -> pd.DataFrame:
    """Section 10 lists "the three pillar sub-scores" as a required
    leaderboard output but the blueprint gives no formula for one -- it
    only defines the overall (all-variable) score. This is the natural
    extension using the same machinery: for each pillar, run
    topsis_scores on just that pillar's columns of X, with their
    entropy weights renormalised to sum to 1 within the pillar (the
    renormalisation doesn't change the score -- the D+/D- ratio is scale
    invariant -- but keeps the weights interpretable as a 0-1 vector).
    Returns one 0-100 column per pillar name."""
    out = pd.DataFrame(index=X.index)
    for pillar_name, cols in pillars.items():
        w_pillar = w[cols]
        w_pillar = w_pillar / w_pillar.sum()
        out[pillar_name] = topsis_scores(X[cols], w_pillar)["score"]
    return out
