"""
Tier 3 of DE/BEN (spec D5, D7): read only the relevant 10-K passages with Gemini.

1. Untagged companies from 14_sec_segments.py: extract segment revenue from the segment note.
2. Every Utilities company: extract the fuel mix of owned generation (fossil / renewable / nuclear).

Requires SEC_USER_AGENT and GEMINI_API_KEY. Run from data/pipeline/nz after 14:
  uv run python 16_segment_notes.py
Outputs: ../../out/nz/segment_notes.csv   (ticker, member, revenue, fiscal_year, filing_url, quote)
         ../../out/nz/note_status.csv     (ticker, status: extracted | not-found | no-10k | no-cik | error)
         ../../out/nz/generation_mix.csv  (ticker, status, fossil_share, renewable_share, nuclear_share, basis, quote)
"""
import argparse
import os
from pathlib import Path

import pandas as pd

from nzlib.edgar import GENERATION_MIX_PATTERNS, SEGMENT_PATTERNS, filing_url, find_sections, html_to_text, latest_10k
from nzlib.gemini import DEFAULT_MODEL, GeminiJson, google_generate
from nzlib.sec import client_from_env, normalise_ticker

OUT_DIR = Path("../../out/nz")
CACHE_DIR = Path("../../raw/nz/gemini_cache")
UNIVERSE_PATH = Path("../../out/sp500_esg_financials_raw.csv")
SHARE_SUM_LIMIT = 1.05
# A generation-mix table for a multi-subsidiary holding company (e.g. Southern Company's Alabama
# Power / Georgia Power / Mississippi Power breakdowns, or Dominion's Virginia Power / DESC /
# Contracted Energy sections) needs a wider window and more slots than the old 8_000/2 -- with
# those, find_sections only ever grabbed one narrow, often irrelevant, mention of "mix" per company.
MIX_WINDOW = 10_000
MIX_MAX_SECTIONS = 3

NOTE_SCHEMA = {
    "type": "object",
    "properties": {
        "fiscal_year": {"type": "integer"},
        "segments": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "revenue_usd_millions": {"type": "number"},
                    "quote": {"type": "string"},
                },
                "required": ["name", "revenue_usd_millions", "quote"],
            },
        },
    },
    "required": ["fiscal_year", "segments"],
}

MIX_SCHEMA = {
    "type": "object",
    "properties": {
        "found": {"type": "boolean"},
        "fossil_share": {"type": "number"},
        "renewable_share": {"type": "number"},
        "nuclear_share": {"type": "number"},
        "basis": {"type": "string", "enum": ["owned_generation_mwh", "capacity_mw", "other"]},
        "quote": {"type": "string"},
    },
    "required": ["found", "fossil_share", "renewable_share", "nuclear_share", "basis", "quote"],
}


def note_prompt(company: str, excerpts: list[str]) -> str:
    return (
        f"These are excerpts from the latest 10-K of {company}.\n"
        "List the company's reportable segments with their external revenue for the most recent fiscal year, "
        "in USD millions, exactly as reported. Exclude totals, eliminations and corporate/other reconciling lines. "
        "Quote the table row for each segment. If no segment revenue is disclosed, return an empty list. "
        "Use fiscal_year 0 if not stated.\n\nExcerpts:\n" + "\n\n---\n\n".join(excerpts)
    )


def mix_prompt(company: str, excerpts: list[str]) -> str:
    return (
        f"These are excerpts from the latest 10-K of {company}, a utility.\n"
        "Give the share of electricity generated by the company's own power plants in the most recent year, by "
        "fuel, as fractions between 0 and 1: fossil (coal, natural gas, oil), renewable (wind, solar, hydro, "
        "biomass, geothermal; battery storage discharge excluded) and nuclear.\n"
        "Prefer generation in MWh. If generation is not given, use net generating capacity in MW instead and set "
        "basis to capacity_mw. If the excerpts show owned generation or capacity broken out by several operating "
        "subsidiaries in the same unit, add the subsidiaries' amounts together before computing shares; if only "
        "one subsidiary gives a usable breakdown, use that one and say so in the quote. Exclude purchased power, "
        "market/wholesale purchases and battery storage from both the fossil/renewable/nuclear amounts and the "
        "total you divide by -- those are not the company's own generation.\n"
        "Quote the exact figures you used (e.g. 'Coal 43%, Nuclear 19%, Natural Gas 22%, Renewables 16%' or "
        "'Natural Gas 24,314 MW, Solar 7,932 MW, Nuclear 3,502 MW, Coal 215 MW'), then compute each share as that "
        "fuel's amount divided by the sum of the fossil + renewable + nuclear amounts only.\n"
        "If the excerpts do not state a mix for the company's own generation, set found=false and all shares to "
        "0.\n\nExcerpts:\n" + "\n\n---\n\n".join(excerpts)
    )


def extract_mix(gemini, company: str, text: str, window: int = MIX_WINDOW, max_sections: int = MIX_MAX_SECTIONS) -> dict:
    """Runs find_sections + the Gemini mix prompt against one filing's text; returns a row dict with
    status extracted/not-found plus the share/basis/quote fields (None when not-found). Pure of I/O
    beyond the injected `gemini` callable, so it's unit-testable without SEC or network access."""
    row = {"status": None, "fossil_share": None, "renewable_share": None, "nuclear_share": None, "basis": None, "quote": None}
    excerpts = find_sections(text, GENERATION_MIX_PATTERNS, window=window, max_sections=max_sections)
    response = gemini(mix_prompt(company, excerpts), MIX_SCHEMA) if excerpts else {"found": False}
    shares_sum = response.get("fossil_share", 0) + response.get("renewable_share", 0) + response.get("nuclear_share", 0)
    if response.get("found") and 0 < shares_sum <= SHARE_SUM_LIMIT:
        row.update({k: response[k] for k in ["fossil_share", "renewable_share", "nuclear_share", "basis", "quote"]})
        row["status"] = "extracted"
    else:
        row["status"] = "not-found"
    return row


def filing_text(sec, ciks: dict, ticker: str) -> tuple[str | None, str | None, str]:
    """Returns (status, url, text); status None means the filing text is available."""
    cik = ciks.get(normalise_ticker(ticker))
    if cik is None:
        return "no-cik", None, ""
    meta = latest_10k(sec.submissions(cik))
    if meta is None:
        return "no-10k", None, ""
    url = filing_url(cik, meta["accession"], meta["primary_document"])
    return None, url, html_to_text(sec.get(url).text)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default=os.environ.get("GEMINI_MODEL", DEFAULT_MODEL))
    parser.add_argument(
        "--mix-only",
        action="store_true",
        help="Skip the untagged-segment-notes loop (segment_notes.csv/note_status.csv are left untouched) "
        "and only (re)run the utility generation-mix extraction.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise SystemExit("Set GEMINI_API_KEY (free tier, gemini-3.5-flash; override with --model/GEMINI_MODEL).")
    sec = client_from_env()
    gemini = GeminiJson(google_generate(api_key), CACHE_DIR, model=args.model)
    ciks = sec.cik_map()

    universe = pd.read_csv(UNIVERSE_PATH, usecols=["ticker", "company_name", "sector"]).set_index("ticker")
    utilities = universe.index[universe["sector"] == "Utilities"].tolist()

    if not args.mix_only:
        status = pd.read_csv(OUT_DIR / "segments_status.csv")
        untagged = status.loc[status["status"] == "untagged", "ticker"].tolist()

        note_rows, note_status = [], []
        for ticker in untagged:
            try:
                state, url, text = filing_text(sec, ciks, ticker)
                if state is None:
                    excerpts = find_sections(text, SEGMENT_PATTERNS, window=12_000, max_sections=2)
                    response = gemini(note_prompt(universe.at[ticker, "company_name"], excerpts), NOTE_SCHEMA) if excerpts else {"segments": []}
                    for s in response["segments"]:
                        note_rows.append(
                            {"ticker": ticker, "member": s["name"], "revenue": s["revenue_usd_millions"] * 1e6,
                             "fiscal_year": response.get("fiscal_year") or None, "filing_url": url, "quote": s["quote"]}
                        )
                    state = "extracted" if response["segments"] else "not-found"
            except Exception as exc:  # noqa: BLE001
                state = f"error: {exc}"
            note_status.append({"ticker": ticker, "status": state})
            print(f"note {ticker}: {state}")

        pd.DataFrame(note_rows, columns=["ticker", "member", "revenue", "fiscal_year", "filing_url", "quote"]).to_csv(
            OUT_DIR / "segment_notes.csv", index=False
        )
        pd.DataFrame(note_status).to_csv(OUT_DIR / "note_status.csv", index=False)

    mix_rows = []
    for ticker in utilities:
        row = {"ticker": ticker, "status": None, "fossil_share": None, "renewable_share": None, "nuclear_share": None, "basis": None, "quote": None}
        try:
            state, _, text = filing_text(sec, ciks, ticker)
            row.update(extract_mix(gemini, universe.at[ticker, "company_name"], text) if state is None else {"status": state})
        except Exception as exc:  # noqa: BLE001
            row["status"] = f"error: {exc}"
        mix_rows.append(row)
        print(f"mix {ticker}: {row['status']}")

    pd.DataFrame(mix_rows).to_csv(OUT_DIR / "generation_mix.csv", index=False)
    print(f"Gemini calls this run (cache misses): {gemini.calls}")


if __name__ == "__main__":
    main()
