"""
Tier 3 of DE/BEN (spec D5, D7): read only the relevant 10-K passages with Gemini.

1. Untagged companies from 14_sec_segments.py: extract segment revenue from the segment note.
2. Every Utilities company: extract the fuel mix of owned generation (fossil / renewable / nuclear).

Requires SEC_USER_AGENT and GEMINI_API_KEY. Run from data/pipeline/nz after 14:
  uv run python 16_segment_notes.py
Outputs: ../../out/nz/segment_notes.csv   (ticker, member, revenue, fiscal_year, filing_url, quote)
         ../../out/nz/note_status.csv     (ticker, status: extracted | not-found | no-10k | no-cik | error)
         ../../out/nz/generation_mix.csv  (ticker, status, fossil_share, renewable_share, nuclear_share, basis, quote)
"""
import argparse
import os
from pathlib import Path

import pandas as pd

from nzlib.edgar import GENERATION_MIX_PATTERNS, SEGMENT_PATTERNS, filing_url, find_sections, html_to_text, latest_10k
from nzlib.gemini import DEFAULT_MODEL, GeminiJson, google_generate
from nzlib.sec import client_from_env, normalise_ticker

OUT_DIR = Path("../../out/nz")
CACHE_DIR = Path("../../raw/nz/gemini_cache")
UNIVERSE_PATH = Path("../../out/sp500_esg_financials_raw.csv")
SHARE_SUM_LIMIT = 1.05

NOTE_SCHEMA = {
    "type": "object",
    "properties": {
        "fiscal_year": {"type": "integer"},
        "segments": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "revenue_usd_millions": {"type": "number"},
                    "quote": {"type": "string"},
                },
                "required": ["name", "revenue_usd_millions", "quote"],
            },
        },
    },
    "required": ["fiscal_year", "segments"],
}

MIX_SCHEMA = {
    "type": "object",
    "properties": {
        "found": {"type": "boolean"},
        "fossil_share": {"type": "number"},
        "renewable_share": {"type": "number"},
        "nuclear_share": {"type": "number"},
        "basis": {"type": "string", "enum": ["owned_generation_mwh", "capacity_mw", "other"]},
        "quote": {"type": "string"},
    },
    "required": ["found", "fossil_share", "renewable_share", "nuclear_share", "basis", "quote"],
}


def note_prompt(company: str, excerpts: list[str]) -> str:
    return (
        f"These are excerpts from the latest 10-K of {company}.\n"
        "List the company's reportable segments with their external revenue for the most recent fiscal year, "
        "in USD millions, exactly as reported. Exclude totals, eliminations and corporate/other reconciling lines. "
        "Quote the table row for each segment. If no segment revenue is disclosed, return an empty list. "
        "Use fiscal_year 0 if not stated.\n\nExcerpts:\n" + "\n\n---\n\n".join(excerpts)
    )


def mix_prompt(company: str, excerpts: list[str]) -> str:
    return (
        f"These are excerpts from the latest 10-K of {company}, a utility.\n"
        "Give the share of electricity generated by the company's own plants in the most recent year by fuel, as "
        "fractions between 0 and 1: fossil (coal, gas, oil), renewable (wind, solar, hydro, biomass, geothermal, "
        "batteries discharge excluded) and nuclear. Prefer generation in MWh; use capacity only if generation is not "
        "given and set basis accordingly. If the excerpts do not state a mix, set found=false and all shares to 0. "
        "Quote the supporting sentence or table row.\n\nExcerpts:\n" + "\n\n---\n\n".join(excerpts)
    )


def filing_text(sec, ciks: dict, ticker: str) -> tuple[str | None, str | None, str]:
    """Returns (status, url, text); status None means the filing text is available."""
    cik = ciks.get(normalise_ticker(ticker))
    if cik is None:
        return "no-cik", None, ""
    meta = latest_10k(sec.submissions(cik))
    if meta is None:
        return "no-10k", None, ""
    url = filing_url(cik, meta["accession"], meta["primary_document"])
    return None, url, html_to_text(sec.get(url).text)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default=os.environ.get("GEMINI_MODEL", DEFAULT_MODEL))
    return parser.parse_args()


def main():
    args = parse_args()
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise SystemExit("Set GEMINI_API_KEY (free tier, gemini-3.5-flash; override with --model/GEMINI_MODEL).")
    sec = client_from_env()
    gemini = GeminiJson(google_generate(api_key), CACHE_DIR, model=args.model)
    ciks = sec.cik_map()

    universe = pd.read_csv(UNIVERSE_PATH, usecols=["ticker", "company_name", "sector"]).set_index("ticker")
    status = pd.read_csv(OUT_DIR / "segments_status.csv")
    untagged = status.loc[status["status"] == "untagged", "ticker"].tolist()
    utilities = universe.index[universe["sector"] == "Utilities"].tolist()

    note_rows, note_status = [], []
    for ticker in untagged:
        try:
            state, url, text = filing_text(sec, ciks, ticker)
            if state is None:
                excerpts = find_sections(text, SEGMENT_PATTERNS, window=12_000, max_sections=2)
                response = gemini(note_prompt(universe.at[ticker, "company_name"], excerpts), NOTE_SCHEMA) if excerpts else {"segments": []}
                for s in response["segments"]:
                    note_rows.append(
                        {"ticker": ticker, "member": s["name"], "revenue": s["revenue_usd_millions"] * 1e6,
                         "fiscal_year": response.get("fiscal_year") or None, "filing_url": url, "quote": s["quote"]}
                    )
                state = "extracted" if response["segments"] else "not-found"
        except Exception as exc:  # noqa: BLE001
            state = f"error: {exc}"
        note_status.append({"ticker": ticker, "status": state})
        print(f"note {ticker}: {state}")

    mix_rows = []
    for ticker in utilities:
        row = {"ticker": ticker, "status": None, "fossil_share": None, "renewable_share": None, "nuclear_share": None, "basis": None, "quote": None}
        try:
            state, _, text = filing_text(sec, ciks, ticker)
            if state is None:
                excerpts = find_sections(text, GENERATION_MIX_PATTERNS, window=8_000, max_sections=2)
                response = gemini(mix_prompt(universe.at[ticker, "company_name"], excerpts), MIX_SCHEMA) if excerpts else {"found": False}
                shares_sum = response.get("fossil_share", 0) + response.get("renewable_share", 0) + response.get("nuclear_share", 0)
                if response.get("found") and 0 < shares_sum <= SHARE_SUM_LIMIT:
                    row.update({k: response[k] for k in ["fossil_share", "renewable_share", "nuclear_share", "basis", "quote"]})
                    state = "extracted"
                else:
                    state = "not-found"
            row["status"] = state
        except Exception as exc:  # noqa: BLE001
            row["status"] = f"error: {exc}"
        mix_rows.append(row)
        print(f"mix {ticker}: {row['status']}")

    pd.DataFrame(note_rows, columns=["ticker", "member", "revenue", "fiscal_year", "filing_url", "quote"]).to_csv(
        OUT_DIR / "segment_notes.csv", index=False
    )
    pd.DataFrame(note_status).to_csv(OUT_DIR / "note_status.csv", index=False)
    pd.DataFrame(mix_rows).to_csv(OUT_DIR / "generation_mix.csv", index=False)
    print(f"Gemini calls this run (cache misses): {gemini.calls}")


if __name__ == "__main__":
    main()
